.TH "src/include Directory Reference" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsubcommands\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalignmentsRetrieval\&.h\fP"
.br
.ti -1c
.RI "file \fBbarcodesComparison\&.h\fP"
.br
.ti -1c
.RI "file \fBbarcodesExtraction\&.h\fP"
.br
.ti -1c
.RI "file \fBgzIndex\&.h\fP"
.br
.ti -1c
.RI "file \fBindexManagementBam\&.h\fP"
.br
.ti -1c
.RI "file \fBindexManagementFastq\&.h\fP"
.br
.ti -1c
.RI "file \fBreadsRetrieval\&.h\fP"
.br
.ti -1c
.RI "file \fBreverseComplement\&.h\fP"
.br
.ti -1c
.RI "file \fBrobin_hood\&.h\fP"
.br
.ti -1c
.RI "file \fButils\&.h\fP"
.br
.in -1c
