.TH "includoc/barcodesExtraction.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/barcodesExtraction.h
.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br
\fC#include 'robin_hood\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "robin_hood::unordered_set< \fBbarcode\fP > \fBextractBarcodesBitsFromRegion_BamReader\fP (BamReader &reader, string region)"
.br
.ti -1c
.RI "robin_hood::unordered_set< string > \fBextractBarcodesSeqsFromRegion_BamReader\fP (BamReader &reader, string region)"
.br
.ti -1c
.RI "robin_hood::unordered_set< \fBbarcode\fP > \fBextractBarcodesBitsFromRegion\fP (string bamFile, string region)"
.br
.ti -1c
.RI "robin_hood::unordered_set< string > \fBextractBarcodesSeqsFromRegion\fP (string bamFile, string region)"
.br
.ti -1c
.RI "robin_hood::unordered_set< \fBbarcode\fP > \fBextractBarcodesBitsFromBAM\fP (string bamFile)"
.br
.ti -1c
.RI "robin_hood::unordered_set< string > \fBextractBarcodesSeqsFromBAM\fP (string bamFile)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "robin_hood::unordered_set<\fBbarcode\fP> extractBarcodesBitsFromBAM (string bamFile)"
Extract all the barcodes of a given BAM file, in binary representation\&.
.PP
\fBParameters\fP
.RS 4
\fIbamFile\fP bamFile BAM file to extract barcodes from 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the BAM file, in binary representation 
.RE
.PP

.SS "robin_hood::unordered_set<\fBbarcode\fP> extractBarcodesBitsFromRegion (string bamFile, string region)"
Extract the barcodes of a given region, in binary representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to extract barcodes from 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region, in binary representation 
.RE
.PP

.SS "robin_hood::unordered_set<\fBbarcode\fP> extractBarcodesBitsFromRegion_BamReader (BamReader & reader, string region)"
Extract the barcodes of a given region, in binary representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP BamReader open on the desired BAM file 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region 
.RE
.PP

.SS "robin_hood::unordered_set<string> extractBarcodesSeqsFromBAM (string bamFile)"
Extract all the barcodes of a given BAM file, in string representation\&.
.PP
\fBParameters\fP
.RS 4
\fIbamFile\fP bamFile BAM file to extract barcodes from 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the BAM file, in string representation 
.RE
.PP

.SS "robin_hood::unordered_set<string> extractBarcodesSeqsFromRegion (string bamFile, string region)"
Extract the barcodes of a given region, in string representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to extract barcodes from 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region, in binary string 
.RE
.PP

.SS "robin_hood::unordered_set<string> extractBarcodesSeqsFromRegion_BamReader (BamReader & reader, string region)"
Extract the barcodes of a given region, in string representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP BamReader open on the desired BAM file 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
