.TH "includoc/barcodesComparison.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/barcodesComparison.h
.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br
\fC#include 'indexManagementBam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhashPairs\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned \fBcountCommonBarcodes\fP (robin_hood::unordered_set< \fBbarcode\fP > barcodes1, robin_hood::unordered_set< \fBbarcode\fP > barcodes2)"
.br
.ti -1c
.RI "robin_hood::unordered_map< pair< string, string >, unsigned, \fBhashPairs\fP > \fBcomputePairwiseCommonBarcounts\fP (robin_hood::unordered_map< string, robin_hood::unordered_set< \fBbarcode\fP >> regionsBarcodes)"
.br
.ti -1c
.RI "robin_hood::unordered_map< pair< string, string >, unsigned, \fBhashPairs\fP > \fBcompareRegions\fP (string bamFile, string regions)"
.br
.ti -1c
.RI "void \fBcomputeCommonBarcodesCounts\fP (robin_hood::unordered_map< pair< string, string >, unsigned, \fBhashPairs\fP > &counts, \fBBarcodesOffsetsIndex\fP &\fBBarcodesOffsetsIndex\fP, BamReader &reader, const RefVector &rv, int size, string &qRegion)"
.br
.ti -1c
.RI "robin_hood::unordered_map< pair< string, string >, unsigned, \fBhashPairs\fP > \fBcompareContig\fP (string bamFile, \fBBarcodesOffsetsIndex\fP &\fBBarcodesOffsetsIndex\fP, string contig, int size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "robin_hood::unordered_map<pair<string, string>, unsigned, \fBhashPairs\fP> compareContig (string bamFile, \fBBarcodesOffsetsIndex\fP & BarcodesOffsetsIndex, string contig, int size)"
Compare the barcodes of a given contig's extremities to the barcodes of other contigs' extremities\&.
.PP
\fBParameters\fP
.RS 4
\fIbamFile\fP BAM file to compare contigs' extremities barcodes from 
.br
\fIBarcodesOffsetsIndex\fP barcode index associating barcodes to the set of BamRegion they appear in 
.br
\fIcontig\fP name of the contig of interest 
.br
\fIsize\fP size of the contigs extremities to consider 
.RE
.PP
\fBReturns\fP
.RS 4
a map associating pairs of contigs' extremities to their number of common barcodes 
.RE
.PP

.SS "robin_hood::unordered_map<pair<string, string>, unsigned, \fBhashPairs\fP> compareRegions (string bamFile, string regions)"
Compute the number of barcodes that are shared between all possible pair of regions contained in a file\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to compute common barcodes from 
.br
\fIregions\fP file containing a list of regions formatted as chromosome:startPosition-endPosition 
.RE
.PP
\fBReturns\fP
.RS 4
a map associating all possible pairs of regions to their number of common barcodes 
.RE
.PP

.SS "void computeCommonBarcodesCounts (robin_hood::unordered_map< pair< string, string >, unsigned, \fBhashPairs\fP > & counts, \fBBarcodesOffsetsIndex\fP & BarcodesOffsetsIndex, BamReader & reader, const RefVector & rv, int size, string & qRegion)"
Compute the number of barcodes that are shared between a given contig's extremity and other contigs' extremities\&.
.PP
\fBParameters\fP
.RS 4
\fIcounts\fP map associating pairs of contigs' extremities to their number of common barcodes 
.br
\fIBarcodesOffsetsIndex\fP barcode index associating barcodes to the set of BamRegion they appear in 
.br
\fIreader\fP BamReader open on the desired BAM file 
.br
\fIrv\fP vector containing the information (name and length) about reference sequences 
.br
\fIsize\fP size of the contigs extremities to consider 
.br
\fIqRegion\fP region of the contig extremity of interest 
.RE
.PP

.SS "robin_hood::unordered_map<pair<string, string>, unsigned, \fBhashPairs\fP> computePairwiseCommonBarcounts (robin_hood::unordered_map< string, robin_hood::unordered_set< \fBbarcode\fP >> regionsBarcodes)"
Compute the number of barcodes that are shared between all possible pair of regions contained in a map\&.
.PP
\fBParameters\fP
.RS 4
\fIregionsBarcodes\fP map associating every region of interest to its set of barcodes 
.RE
.PP
\fBReturns\fP
.RS 4
a map associating all possible pairs of regions to their number of common barcodes 
.RE
.PP

.SS "unsigned countCommonBarcodes (robin_hood::unordered_set< \fBbarcode\fP > barcodes1, robin_hood::unordered_set< \fBbarcode\fP > barcodes2)"
Count the number of common barcodes between two sets of barcodes\&.
.PP
\fBParameters\fP
.RS 4
\fIbarcodes1\fP first set of barcodes 
.br
\fIbarcodes2\fP second set of barcodes 
.RE
.PP
\fBReturns\fP
.RS 4
the number of common barcodes between the two sets 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
