.TH "src/barcodesExtraction.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/barcodesExtraction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'barcodesExtraction\&.h'\fP
.br
\fC#include 'reverseComplement\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrobin_hood::unordered_set\fP< \fBbarcode\fP > \fBextractBarcodesBitsFromRegion_BamReader\fP (BamReader &reader, string region)"
.br
.ti -1c
.RI "\fBrobin_hood::unordered_set\fP< string > \fBextractBarcodesSeqsFromRegion_BamReader\fP (BamReader &reader, string region)"
.br
.ti -1c
.RI "\fBrobin_hood::unordered_set\fP< \fBbarcode\fP > \fBextractBarcodesBitsFromRegion\fP (string bamFile, string region)"
.br
.ti -1c
.RI "\fBrobin_hood::unordered_set\fP< string > \fBextractBarcodesSeqsFromRegion\fP (string bamFile, string region)"
.br
.ti -1c
.RI "\fBrobin_hood::unordered_set\fP< \fBbarcode\fP > \fBextractBarcodesBitsFromBAM\fP (string bamFile)"
.br
.ti -1c
.RI "\fBrobin_hood::unordered_set\fP< string > \fBextractBarcodesSeqsFromBAM\fP (string bamFile)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBrobin_hood::unordered_set\fP<\fBbarcode\fP> extractBarcodesBitsFromBAM (string bamFile)"
Extract all the barcodes of a given BAM file, in binary representation\&.
.PP
\fBParameters\fP
.RS 4
\fIbamFile\fP bamFile BAM file to extract barcodes from 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the BAM file, in binary representation 
.RE
.PP

.PP
Definition at line 88 of file barcodesExtraction\&.cpp\&.
.SS "\fBrobin_hood::unordered_set\fP<\fBbarcode\fP> extractBarcodesBitsFromRegion (string bamFile, string region)"
Extract the barcodes of a given region, in binary representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to extract barcodes from 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region, in binary representation 
.RE
.PP

.PP
Definition at line 59 of file barcodesExtraction\&.cpp\&.
.SS "\fBrobin_hood::unordered_set\fP<\fBbarcode\fP> extractBarcodesBitsFromRegion_BamReader (BamReader & reader, string region)"
Extract the barcodes of a given region, in binary representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP BamReader open on the desired BAM file 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region 
.RE
.PP

.PP
Definition at line 4 of file barcodesExtraction\&.cpp\&.
.SS "\fBrobin_hood::unordered_set\fP<string> extractBarcodesSeqsFromBAM (string bamFile)"
Extract all the barcodes of a given BAM file, in string representation\&.
.PP
\fBParameters\fP
.RS 4
\fIbamFile\fP bamFile BAM file to extract barcodes from 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the BAM file, in string representation 
.RE
.PP

.PP
Definition at line 131 of file barcodesExtraction\&.cpp\&.
.SS "\fBrobin_hood::unordered_set\fP<string> extractBarcodesSeqsFromRegion (string bamFile, string region)"
Extract the barcodes of a given region, in string representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to extract barcodes from 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region, in binary string 
.RE
.PP

.PP
Definition at line 77 of file barcodesExtraction\&.cpp\&.
.SS "\fBrobin_hood::unordered_set\fP<string> extractBarcodesSeqsFromRegion_BamReader (BamReader & reader, string region)"
Extract the barcodes of a given region, in string representation\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP BamReader open on the desired BAM file 
.br
\fIregion\fP region of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the barcodes present in the region 
.RE
.PP

.PP
Definition at line 48 of file barcodesExtraction\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
