.TH "includoc/subcommands/compare.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/subcommands/compare.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandCompare\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandCompare (int argc, char * argv[])"
Compare the barcodes of a given region to all other regions, or the barcodes contained in a contig's extremities to all other contigs' extremities 
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
