.TH "hashPairs" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hashPairs
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <barcodesComparison\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class T1 , class T2 > size_t \fBoperator()\fP (const pair< T1, T2 > &p) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure defining a hash function, to hash a pair of any kind\&. Required to use a pair<string, string> as key in the maps used for the compareRegions and compareContig functions\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class T1 , class T2 > size_t hashPairs::operator() (const pair< T1, T2 > & p) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
