.TH "src/subcommands/help.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/subcommands/help.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'subcommands/help\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandHelp\fP (std::string subcommand)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandHelp (std::string subcommand)"

.PP
Definition at line 3 of file help\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
