.TH "src/subcommands/indexFastq.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/subcommands/indexFastq.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'subcommands/indexFastq\&.h'\fP
.br
\fC#include 'subcommands/help\&.h'\fP
.br
\fC#include 'indexManagementFastq\&.h'\fP
.br
\fC#include 'gzIndex\&.h'\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandIndexFastq\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandIndexFastq (int argc, char * argv[])"
Index the fastq file passed in the parameters 
.PP
Definition at line 11 of file indexFastq\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
