.TH "src/subcommands/indexBam.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/subcommands/indexBam.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'subcommands/indexBam\&.h'\fP
.br
\fC#include 'subcommands/help\&.h'\fP
.br
\fC#include 'indexManagementBam\&.h'\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandIndexBam\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandIndexBam (int argc, char * argv[])"
Index the BAM file passed in the parameters 
.PP
Definition at line 10 of file indexBam\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
