.TH "includoc/indexManagementBam.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/indexManagementBam.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'robin_hood\&.h'\fP
.br
\fC#include 'api/BamAux\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef robin_hood::unordered_map< \fBbarcode\fP, vector< int64_t > > \fBBarcodesOffsetsIndex\fP"
.br
.ti -1c
.RI "typedef robin_hood::unordered_map< \fBbarcode\fP, vector< pair< int32_t, int32_t > > > \fBBarcodesPositionsIndex\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBarcodesPositionsIndex\fP \fBindexBarcodesPositionsFromBam\fP (string bamFile, bool primary, unsigned quality)"
.br
.ti -1c
.RI "void \fBsaveBarcodesPositionsIndex\fP (\fBBarcodesPositionsIndex\fP &index, string file)"
.br
.ti -1c
.RI "\fBBarcodesPositionsIndex\fP \fBloadBarcodesPositionsIndex\fP (string file)"
.br
.ti -1c
.RI "\fBBarcodesOffsetsIndex\fP \fBindexBarcodesOffsetsFromBam\fP (string bamFile, bool primary, unsigned quality)"
.br
.ti -1c
.RI "void \fBsaveBarcodesOffsetsIndex\fP (\fBBarcodesOffsetsIndex\fP &index, string file)"
.br
.ti -1c
.RI "\fBBarcodesOffsetsIndex\fP \fBloadBarcodesOffsetsIndex\fP (string file)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef robin_hood::unordered_map<\fBbarcode\fP, vector<int64_t> > \fBBarcodesOffsetsIndex\fP"

.SS "typedef robin_hood::unordered_map<\fBbarcode\fP, vector<pair<int32_t, int32_t> > > \fBBarcodesPositionsIndex\fP"

.SH "Function Documentation"
.PP 
.SS "\fBBarcodesOffsetsIndex\fP indexBarcodesOffsetsFromBam (string bamFile, bool primary, unsigned quality)"
Index the offsets of the barcodes contained in a given BAM file\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to build the index from 
.br
\fIprimary\fP whether to only index primary alignments or not 
.br
\fIquality\fP minimum quality to index an alignment 
.RE
.PP
\fBReturns\fP
.RS 4
the barcode index associating barcodes to the set of offsets they occur at 
.RE
.PP

.SS "\fBBarcodesPositionsIndex\fP indexBarcodesPositionsFromBam (string bamFile, bool primary, unsigned quality)"
Index the (chromosome, begPosition) pairs of the barcodes contained in a given BAM file\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP bamFile BAM file to build the index from 
.br
\fIprimary\fP whether to only index primary alignments or not 
.br
\fIquality\fP minimum quality to index an alignment 
.RE
.PP
\fBReturns\fP
.RS 4
the barcode positions index associating barcodes to the set of (chromosome, begPosition) pairs they occur at 
.RE
.PP

.SS "\fBBarcodesOffsetsIndex\fP loadBarcodesOffsetsIndex (string file)"
Load the barcode index stored in a given file\&.
.PP
\fBParameters\fP
.RS 4
\fIfile\fP file where the barcode offsets index is stored 
.RE
.PP
\fBReturns\fP
.RS 4
the barcode offsets index filled with the data contained in the file 
.RE
.PP

.SS "\fBBarcodesPositionsIndex\fP loadBarcodesPositionsIndex (string file)"
Load the barcode positions index stored in a given file\&.
.PP
\fBParameters\fP
.RS 4
\fIfile\fP file where the barcode positions index is stored 
.RE
.PP
\fBReturns\fP
.RS 4
the barcode positions index filled with the data contained in the file 
.RE
.PP

.SS "void saveBarcodesOffsetsIndex (\fBBarcodesOffsetsIndex\fP & index, string file)"
Save the content of the barcode index in a given file\&.
.PP
\fBParameters\fP
.RS 4
\fIBarcodesOffsetsIndex\fP barcode offsets index to save 
.br
\fIfile\fP file where to store the index 
.RE
.PP

.SS "void saveBarcodesPositionsIndex (\fBBarcodesPositionsIndex\fP & index, string file)"
Save the content of the barcode positions index in a given file\&.
.PP
\fBParameters\fP
.RS 4
\fIBarcodesPositionsIndex\fP barcode positions index to save 
.br
\fIfile\fP file where to store the index 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
