.TH "src/main.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'subcommands/compare\&.h'\fP
.br
\fC#include 'subcommands/extract\&.h'\fP
.br
\fC#include 'subcommands/help\&.h'\fP
.br
\fC#include 'subcommands/indexBam\&.h'\fP
.br
\fC#include 'subcommands/queryBam\&.h'\fP
.br
\fC#include 'subcommands/indexFastq\&.h'\fP
.br
\fC#include 'subcommands/queryFastq\&.h'\fP
.br
\fC#include <set>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 15 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
