.TH "robin_hood::detail::WrapKeyEqual< T >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::detail::WrapKeyEqual< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.PP
Inherits T\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWrapKeyEqual\fP ()=default"
.br
.ti -1c
.RI "\fBWrapKeyEqual\fP (T const &o) noexcept(noexcept(T(std::declval< T const & >())))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct robin_hood::detail::WrapKeyEqual< T >"

.PP
Definition at line 844 of file robin_hood\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBrobin_hood::detail::WrapKeyEqual\fP< T >::\fBWrapKeyEqual\fP ()\fC [default]\fP"

.SS "template<typename T > \fBrobin_hood::detail::WrapKeyEqual\fP< T >::\fBWrapKeyEqual\fP (T const & o)\fC [inline]\fP, \fC [explicit]\fP, \fC [noexcept]\fP"

.PP
Definition at line 846 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
