.TH "robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, true >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddOrFree\fP (void *ptr, size_t \fBROBIN_HOOD_UNUSED\fP(numBytes)) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, size_t MinSize, size_t MaxSize>
.br
struct robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, true >"

.PP
Definition at line 541 of file robin_hood\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , size_t MinSize, size_t MaxSize> void \fBrobin_hood::detail::NodeAllocator\fP< T, MinSize, MaxSize, true >::addOrFree (void * ptr, size_t  ROBIN_HOOD_UNUSEDnumBytes)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 544 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
