.TH "robin_hood::hash< T * >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::hash< T * >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (T *ptr) const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct robin_hood::hash< T * >"

.PP
Definition at line 789 of file robin_hood\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > size_t \fBrobin_hood::hash\fP< T * >::operator() (T * ptr) const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 790 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
