.TH "robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, false >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, false >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.PP
Inherits \fBrobin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T, size_t MinSize, size_t MaxSize>
.br
struct robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, false >"

.PP
Definition at line 550 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
