.TH "includoc/utils.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/utils.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'api/BamReader\&.h'\fP
.br
\fC#include 'api/BamIndex\&.h'\fP
.br
\fC#include 'api/BamAux\&.h'\fP
.br
\fC#include 'robin_hood\&.h'\fP
.br
\fC#include <sstream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBARCODE_SIZE\fP   16"
.br
.ti -1c
.RI "#define \fBBXTAG\fP   'BX:Z'"
.br
.ti -1c
.RI "#define \fBRXTAG\fP   'RX:Z'"
.br
.ti -1c
.RI "#define \fBno_argument\fP   0"
.br
.ti -1c
.RI "#define \fBrequired_argument\fP   1"
.br
.ti -1c
.RI "#define \fBoptional_argument\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef string \fBbarcode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBonlyContainsNucleotides\fP (string \fBbarcode\fP)"
.br
.ti -1c
.RI "\fBbarcode\fP \fBstringToBarcode\fP (const string &str)"
.br
.ti -1c
.RI "string \fBbarcodeToString\fP (\fBbarcode\fP b)"
.br
.ti -1c
.RI "vector< string > \fBsplitString\fP (string s, string delimiter)"
.br
.ti -1c
.RI "BamRegion \fBstringToBamRegion\fP (BamReader &reader, string s)"
.br
.ti -1c
.RI "string \fBconvertToSam\fP (const BamAlignment &a, RefVector m_references)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBCONSIDER_RX\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BARCODE_SIZE   16"

.SS "#define BXTAG   'BX:Z'"

.SS "#define no_argument   0"

.SS "#define optional_argument   2"

.SS "#define required_argument   1"

.SS "#define RXTAG   'RX:Z'"

.SH "Typedef Documentation"
.PP 
.SS "typedef string \fBbarcode\fP"

.SH "Function Documentation"
.PP 
.SS "string barcodeToString (\fBbarcode\fP b)"
Translate a barcode to a string\&.
.PP
\fBParameters\fP
.RS 4
\fIb\fP barcode to convert 
.RE
.PP
\fBReturns\fP
.RS 4
the barcode in string representation 
.RE
.PP

.SS "string convertToSam (const BamAlignment & a, RefVector m_references)"
Translate a BamAlignment to a SAM-like string\&.
.PP
\fBParameters\fP
.RS 4
\fIa\fP BamAlignment to translate 
.br
\fIm_references\fP vector containing the information (name and length) about reference sequences 
.RE
.PP
\fBReturns\fP
.RS 4
a SAM-like string summarizing the information of a 
.RE
.PP

.SS "bool onlyContainsNucleotides (string barcode)"
Verify if a barcode is only made up of nucleotides\&.
.PP
\fBParameters\fP
.RS 4
\fIthe\fP barcode to analyse, in string representation 
.RE
.PP
\fBReturns\fP
.RS 4
true if the barcode only contains nucleotides, false otherwise 
.RE
.PP

.SS "vector<string> splitString (string s, string delimiter)"
Split a string according to a delimiter\&.
.PP
\fBParameters\fP
.RS 4
\fIs\fP string to split 
.br
\fIdelimiter\fP delimiter 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing the splits of the string 
.RE
.PP

.SS "BamRegion stringToBamRegion (BamReader & reader, string s)"
Translate a string to a BamRegion\&.
.PP
\fBParameters\fP
.RS 4
\fIreader\fP BamReader open on the desired BAM file 
.br
\fIs\fP string to translate, formatted as chromosome:startPosition-endPosition 
.RE
.PP
\fBReturns\fP
.RS 4
the BamRegion coressponding to the string s 
.RE
.PP

.SS "\fBbarcode\fP stringToBarcode (const string & str)"
Translate a string to a barcode\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to convert 
.RE
.PP
\fBReturns\fP
.RS 4
the barcode in binary representation 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "bool CONSIDER_RX"

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
