.TH "access" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
access
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gzIndex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBhave\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "struct \fBpoint\fP * \fBlist\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int access::have"

.SS "struct \fBpoint\fP* access::list"

.SS "int access::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
