.TH "src/subcommands/compare.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/subcommands/compare.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'subcommands/compare\&.h'\fP
.br
\fC#include 'subcommands/help\&.h'\fP
.br
\fC#include 'barcodesComparison\&.h'\fP
.br
\fC#include 'indexManagementBam\&.h'\fP
.br
\fC#include <getopt\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandCompare\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandCompare (int argc, char * argv[])"
Compare the barcodes of a given region to all other regions, or the barcodes contained in a contig's extremities to all other contigs' extremities 
.PP
Definition at line 7 of file compare\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
