.TH "src/subcommands/extract.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/subcommands/extract.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'subcommands/extract\&.h'\fP
.br
\fC#include 'subcommands/help\&.h'\fP
.br
\fC#include 'barcodesExtraction\&.h'\fP
.br
\fC#include <getopt\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandExtract\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandExtract (int argc, char * argv[])"
Extract barcodes from a BAM file, according to the parameters passed 
.PP
Definition at line 8 of file extract\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
