.TH "includoc/subcommands/indexFastq.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/subcommands/indexFastq.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandIndexFastq\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandIndexFastq (int argc, char * argv[])"
Index the fastq file passed in the parameters 
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
