.TH "src/readsRetrieval.cpp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/readsRetrieval.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'readsRetrieval\&.h'\fP
.br
\fC#include 'reverseComplement\&.h'\fP
.br
\fC#include <chrono>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodeBits_Stream\fP (ifstream &in, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, \fBbarcode\fP bc)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodeBits\fP (string fastqFile, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, \fBbarcode\fP bc)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcode_Stream\fP (ifstream &reader, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string bc)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcode\fP (string fastqFile, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string bc)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodes_Stream\fP (ifstream &in, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string barcodesList)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodes\fP (string fastqFile, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string barcodesList)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodeBits_Gzip_Stream_Index\fP (FILE *in, struct \fBaccess\fP *gzIndex, \fBBarcodesIndex\fP &barcodesIndex, \fBbarcode\fP bc)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodeBits_Gzip\fP (string fastqFile, \fBBarcodesIndex\fP &barcodesIndex, \fBbarcode\fP bc)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcode_Gzip_Stream_Index\fP (FILE *in, struct \fBaccess\fP *gzIndex, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string \fBbarcode\fP)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcode_Gzip\fP (string fastqFile, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string \fBbarcode\fP)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodes_Gzip_Stream_Index\fP (FILE *in, struct \fBaccess\fP *gzIndex, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string barcodesList)"
.br
.ti -1c
.RI "vector< string > \fBretrieveReadsWithBarcodes_Gzip\fP (string fastqFile, \fBBarcodesIndex\fP &\fBBarcodesIndex\fP, string barcodesList)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "vector<string> retrieveReadsWithBarcode (string fastqFile, \fBBarcodesIndex\fP & BarcodesIndex, string bc)"
Retrieve all the reads that share a given barcode, in a given fastq file\&.
.PP
\fBParameters\fP
.RS 4
\fIfastqFile\fP fastq file to extract reads from 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbc\fP barcode of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 49 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcode_Gzip (string fastqFile, \fBBarcodesIndex\fP & BarcodesIndex, string barcode)"
Retrieve all the reads that share a given barcode, in a given gzipped fastq file, using its index\&.
.PP
\fBParameters\fP
.RS 4
\fIfastqFile\fP gzipped fastq file to extract reads from 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbc\fP barcode of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 124 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcode_Gzip_Stream_Index (FILE * in, struct \fBaccess\fP * gzIndex, \fBBarcodesIndex\fP & BarcodesIndex, string barcode)"
Retrieve all the reads that share a given barcode, in a given gzipped fastq file, using its index\&.
.PP
\fBParameters\fP
.RS 4
\fIin\fP FILE open on the desired gzipped fastq file 
.br
\fIgzIndex\fP index of the gzipped fastq file 
.br
\fIBarcodesIndex\fP barcode index of the gzipped fastq file 
.br
\fIbc\fP barcode of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 120 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcode_Stream (ifstream & reader, \fBBarcodesIndex\fP & BarcodesIndex, string bc)"
Retrieve all the reads that share a given barcode, in a given fastq file\&.
.PP
\fBParameters\fP
.RS 4
\fIin\fP stream open on the desired fastq file 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbc\fP barcode of interest 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 45 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodeBits (string fastqFile, \fBBarcodesIndex\fP & BarcodesIndex, \fBbarcode\fP bc)"
Retrieve all the reads that share a given barcode, in a given fastq file\&.
.PP
\fBParameters\fP
.RS 4
\fIfastqFile\fP fastq file to extract reads from 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbc\fP barcode of interest, in binary representation 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 30 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodeBits_Gzip (string fastqFile, \fBBarcodesIndex\fP & barcodexIndex, \fBbarcode\fP bc)"
Retrieve all the reads that share a given barcode, in a given gzipped fastq file, using its index\&.
.PP
\fBParameters\fP
.RS 4
\fIfastqFile\fP gzipped fastq file to extract reads from 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbc\fP barcode of interest, in binary representation 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 102 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodeBits_Gzip_Stream_Index (FILE * in, struct \fBaccess\fP * gzIndex, \fBBarcodesIndex\fP & barcodexIndex, \fBbarcode\fP bc)"
Retrieve all the reads that share a given barcode, in a given gzipped fastq file, using its index\&.
.PP
\fBParameters\fP
.RS 4
\fIin\fP FILE open on the desired gzipped fastq file 
.br
\fIgzIndex\fP index of the gzipped fastq file 
.br
\fIBarcodesIndex\fP barcode index of the gzipped fastq file 
.br
\fIbc\fP barcode of interest, in binary representation 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 90 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodeBits_Stream (ifstream & in, \fBBarcodesIndex\fP & BarcodesIndex, \fBbarcode\fP bc)"
Retrieve all the reads that share a given barcode, in a given fastq file\&.
.PP
\fBParameters\fP
.RS 4
\fIin\fP stream open on the desired fastq file 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbc\fP barcode of interest, in binary representation 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcode of interest 
.RE
.PP

.PP
Definition at line 5 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodes (string fastqFile, \fBBarcodesIndex\fP & BarcodesIndex, string barcodesList)"
Retrieve all the reads of a fastq file that share a barcode appearing in the list of a given file
.PP
\fBParameters\fP
.RS 4
\fIfastqFile\fP fastq file to extract reads from 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbarcodesList\fP file containing the list of barcodes of interest, with one barcode per line 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcodes of interest 
.RE
.PP

.PP
Definition at line 76 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodes_Gzip (string fastqFile, \fBBarcodesIndex\fP & BarcodesIndex, string barcodesList)"
Retrieve all the reads of a fastq file that share a barcode appearing in the list of a given file
.PP
\fBParameters\fP
.RS 4
\fIfastqFile\fP fastq file to extract reads from 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbarcodesList\fP file containing the list of barcodes of interest, with one barcode per line 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcodes of interest 
.RE
.PP

.PP
Definition at line 151 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodes_Gzip_Stream_Index (FILE * in, struct \fBaccess\fP * gzIndex, \fBBarcodesIndex\fP & BarcodesIndex, string barcodesList)"
Retrieve all the reads of a gzipped fastq file that share a barcode appearing in the list of a given file
.PP
\fBParameters\fP
.RS 4
\fIin\fP FILE open on the desired gzipped fastq file 
.br
\fIgzIndex\fP index of the gzipped fastq file 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbarcodesList\fP file containing the list of barcodes of interest, with one barcode per line 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcodes of interest 
.RE
.PP

.PP
Definition at line 128 of file readsRetrieval\&.cpp\&.
.SS "vector<string> retrieveReadsWithBarcodes_Stream (ifstream & in, \fBBarcodesIndex\fP & BarcodesIndex, string barcodesList)"
Retrieve all the reads of a fastq file that share a barcode appearing in the list of a given file
.PP
\fBParameters\fP
.RS 4
\fIin\fP stream open on the desired fastq file 
.br
\fIBarcodesIndex\fP barcode index of the fastq file 
.br
\fIbarcodesList\fP file containing the list of barcodes of interest, with one barcode per line 
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all the reads with the barcodes of interest 
.RE
.PP

.PP
Definition at line 53 of file readsRetrieval\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
