.TH "rev_comp" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rev_comp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reverseComplement\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBrun\fP (std::string seq)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBrev_comp\fP ()"
.br
.ti -1c
.RI "\fB~rev_comp\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBbuild_instance\fP ()"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBrev_comp\fP * \fB_instance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file reverseComplement\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rev_comp::rev_comp ()\fC [protected]\fP"

.SS "rev_comp::~rev_comp ()\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static void rev_comp::build_instance ()\fC [static]\fP, \fC [protected]\fP"

.SS "static std::string rev_comp::run (std::string seq)\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBrev_comp\fP* rev_comp::_instance\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 11 of file reverseComplement\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
