.TH "robin_hood::detail" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::detail
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBswappable\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBulkPoolAllocator\fP"
.br
.ti -1c
.RI "struct \fBhas_is_transparent\fP"
.br
.ti -1c
.RI "struct \fBhas_is_transparent< T, typename T::is_transparent >\fP"
.br
.ti -1c
.RI "struct \fBidentity_hash\fP"
.br
.ti -1c
.RI "struct \fBNodeAllocator\fP"
.br
.ti -1c
.RI "struct \fBNodeAllocator< T, MinSize, MaxSize, false >\fP"
.br
.ti -1c
.RI "struct \fBNodeAllocator< T, MinSize, MaxSize, true >\fP"
.br
.ti -1c
.RI "class \fBTable\fP"
.br
.ti -1c
.RI "struct \fBWrapHash\fP"
.br
.ti -1c
.RI "struct \fBWrapKeyEqual\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBrotr\fP (T x, unsigned k)"
.br
.ti -1c
.RI "template<typename T > T \fBreinterpret_cast_no_cast_align_warning\fP (void *ptr) noexcept"
.br
.ti -1c
.RI "template<typename T > T \fBreinterpret_cast_no_cast_align_warning\fP (void const *ptr) noexcept"
.br
.ti -1c
.RI "template<typename E , typename\&.\&.\&. Args> void \fBdoThrow\fP (Args &&\&.\&.\&. \fBROBIN_HOOD_UNUSED\fP(args))"
.br
.ti -1c
.RI "template<typename E , typename T , typename\&.\&.\&. Args> T * \fBassertNotNull\fP (T *t, Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename T > T \fBunaligned_load\fP (void const *ptr) noexcept"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename E , typename T , typename\&.\&.\&. Args> T* robin_hood::detail::assertNotNull (T * t, Args &&\&.\&.\&. args)"

.PP
Definition at line 347 of file robin_hood\&.h\&.
.SS "template<typename E , typename\&.\&.\&. Args> void robin_hood::detail::doThrow (Args &&\&.\&.\&.  ROBIN_HOOD_UNUSEDargs)"

.PP
Definition at line 341 of file robin_hood\&.h\&.
.SS "template<typename T > T robin_hood::detail::reinterpret_cast_no_cast_align_warning (void * ptr)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 322 of file robin_hood\&.h\&.
.SS "template<typename T > T robin_hood::detail::reinterpret_cast_no_cast_align_warning (void const * ptr)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 327 of file robin_hood\&.h\&.
.SS "template<typename T > T robin_hood::detail::rotr (T x, unsigned k)"

.PP
Definition at line 314 of file robin_hood\&.h\&.
.SS "template<typename T > T robin_hood::detail::unaligned_load (void const * ptr)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 355 of file robin_hood\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
