.TH "robin_hood::detail::swappable::nothrow< T >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::detail::swappable::nothrow< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = noexcept(\fBswap\fP(std::declval<T&>(), std::declval<T&>()))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct robin_hood::detail::swappable::nothrow< T >"

.PP
Definition at line 566 of file robin_hood\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > const bool \fBrobin_hood::detail::swappable::nothrow\fP< T >::value = noexcept(\fBswap\fP(std::declval<T&>(), std::declval<T&>()))\fC [static]\fP"

.PP
Definition at line 567 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
