.TH "robin_hood::ROBIN_HOOD_STD::alignment_of< T >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::ROBIN_HOOD_STD::alignment_of< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.PP
Inherits integral_constant< std::size_t, alignof(std::remove_all_extents< T >::type)>\&.
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct robin_hood::ROBIN_HOOD_STD::alignment_of< T >"

.PP
Definition at line 244 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
