.TH "robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBulkPoolAllocator\fP () noexcept=default"
.br
.ti -1c
.RI "\fBBulkPoolAllocator\fP (const \fBBulkPoolAllocator\fP &\fBROBIN_HOOD_UNUSED\fP(o)) noexcept"
.br
.ti -1c
.RI "\fBBulkPoolAllocator\fP (\fBBulkPoolAllocator\fP &&o) noexcept"
.br
.ti -1c
.RI "\fBBulkPoolAllocator\fP & \fBoperator=\fP (\fBBulkPoolAllocator\fP &&o) noexcept"
.br
.ti -1c
.RI "\fBBulkPoolAllocator\fP & \fBoperator=\fP (const \fBBulkPoolAllocator\fP &\fBROBIN_HOOD_UNUSED\fP(o)) noexcept"
.br
.ti -1c
.RI "\fB~BulkPoolAllocator\fP () noexcept"
.br
.ti -1c
.RI "void \fBreset\fP () noexcept"
.br
.ti -1c
.RI "T * \fBallocate\fP ()"
.br
.ti -1c
.RI "void \fBdeallocate\fP (T *obj) noexcept"
.br
.ti -1c
.RI "void \fBaddOrFree\fP (void *ptr, const size_t numBytes) noexcept"
.br
.ti -1c
.RI "void \fBswap\fP (\fBBulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs > &other) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256>
.br
class robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >"

.PP
Definition at line 367 of file robin_hood\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::\fBBulkPoolAllocator\fP ()\fC [default]\fP, \fC [noexcept]\fP"

.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::\fBBulkPoolAllocator\fP (const \fBBulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs > & ROBIN_HOOD_UNUSEDo)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 372 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::\fBBulkPoolAllocator\fP (\fBBulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs > && o)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 376 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::~\fBBulkPoolAllocator\fP ()\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 399 of file robin_hood\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::addOrFree (void * ptr, const size_t numBytes)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 438 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> T* \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::allocate ()\fC [inline]\fP"

.PP
Definition at line 416 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::deallocate (T * obj)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 430 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> \fBBulkPoolAllocator\fP& \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::operator= (\fBBulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs > && o)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 383 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> \fBBulkPoolAllocator\fP& \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::operator= (const \fBBulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs > & ROBIN_HOOD_UNUSEDo)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 394 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::reset ()\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 404 of file robin_hood\&.h\&.
.SS "template<typename T , size_t MinNumAllocs = 4, size_t MaxNumAllocs = 256> void \fBrobin_hood::detail::BulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs >::swap (\fBBulkPoolAllocator\fP< T, MinNumAllocs, MaxNumAllocs > & other)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Definition at line 448 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
