.TH "src/subcommands Directory Reference" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/subcommands Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcompare\&.cpp\fP"
.br
.ti -1c
.RI "file \fBextract\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhelp\&.cpp\fP"
.br
.ti -1c
.RI "file \fBindexBam\&.cpp\fP"
.br
.ti -1c
.RI "file \fBindexFastq\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqueryBam\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqueryFastq\&.cpp\fP"
.br
.in -1c
