.TH "includoc/subcommands/extract.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/subcommands/extract.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandExtract\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void subcommandExtract (int argc, char * argv[])"
Extract barcodes from a BAM file, according to the parameters passed 
.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
