.TH "includoc/subcommands/help.h" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includoc/subcommands/help.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVERSION\fP   'LRez v\&.2\&.0'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsubcommandHelp\fP (string subcommand)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define VERSION   'LRez v\&.2\&.0'"

.SH "Function Documentation"
.PP 
.SS "void subcommandHelp (string subcommand)"
Display usage information\&.
.PP
\fBParameters\fP
.RS 4
\fIsubcommand\fP subcommand to display usage information for 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
