.TH "point" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gzIndex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "off_t \fBout\fP"
.br
.ti -1c
.RI "off_t \fBin\fP"
.br
.ti -1c
.RI "int \fBbits\fP"
.br
.ti -1c
.RI "unsigned char \fBwindow\fP [\fBWINSIZE\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int point::bits"

.SS "off_t point::in"

.SS "off_t point::out"

.SS "unsigned char point::window[\fBWINSIZE\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
