.TH "robin_hood::ROBIN_HOOD_STD::detail_::IntSeqImpl< T, Begin, End, bool >" 3 "Tue Apr 20 2021" "Version 2.0" "LRez" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robin_hood::ROBIN_HOOD_STD::detail_::IntSeqImpl< T, Begin, End, bool >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robin_hood\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIntSeqCombiner\fP"
.br
.ti -1c
.RI "struct \fBIntSeqCombiner< integer_sequence< TValue, Inds0\&.\&.\&. >, integer_sequence< TValue, Inds1\&.\&.\&. > >\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTValue\fP = T"
.br
.ti -1c
.RI "using \fBTResult\fP = typename \fBIntSeqCombiner\fP< typename \fBIntSeqImpl\fP< \fBTValue\fP, Begin, Begin+(End \- Begin)/2,(End \- Begin)/2==1 >::\fBTResult\fP, typename \fBIntSeqImpl\fP< \fBTValue\fP, Begin+(End \- Begin)/2, End,(End \- Begin+1)/2==1 >::\fBTResult\fP >::\fBTResult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, T Begin, T End, bool>
.br
struct robin_hood::ROBIN_HOOD_STD::detail_::IntSeqImpl< T, Begin, End, bool >"

.PP
Definition at line 261 of file robin_hood\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T , T Begin, T End, bool > using \fBrobin_hood::ROBIN_HOOD_STD::detail_::IntSeqImpl\fP< T, Begin, End, bool >::\fBTResult\fP =  typename \fBIntSeqCombiner\fP<typename \fBIntSeqImpl\fP<\fBTValue\fP, Begin, Begin + (End \- Begin) / 2, (End \- Begin) / 2 == 1>::\fBTResult\fP, typename \fBIntSeqImpl\fP<\fBTValue\fP, Begin + (End \- Begin) / 2, End, (End \- Begin + 1) / 2 == 1>::\fBTResult\fP>::\fBTResult\fP"

.PP
Definition at line 278 of file robin_hood\&.h\&.
.SS "template<class T , T Begin, T End, bool > using \fBrobin_hood::ROBIN_HOOD_STD::detail_::IntSeqImpl\fP< T, Begin, End, bool >::\fBTValue\fP =  T"

.PP
Definition at line 262 of file robin_hood\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LRez from the source code\&.
